# Generated by Django 4.2.5 on 2023-10-16 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_order", models.IntegerField(verbose_name="Order id")),
                (
                    "opened_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Opened at"),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Closed at"
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="Is closed"),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="Is processed"),
                ),
                (
                    "name_user",
                    models.CharField(max_length=100, null=True, verbose_name="Name"),
                ),
                (
                    "phone_user",
                    models.CharField(max_length=100, null=True, verbose_name="Phone"),
                ),
                (
                    "address",
                    models.CharField(max_length=100, null=True, verbose_name="Address"),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.CreateModel(
            name="OrderPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="cart.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order position",
                "verbose_name_plural": "Order positions",
                "ordering": ["-count"],
            },
        ),
    ]
