# Generated by Django 4.2.5 on 2023-12-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="id_order",
        ),
        migrations.RemoveField(
            model_name="order",
            name="name_user",
        ),
        migrations.RemoveField(
            model_name="order",
            name="phone_user",
        ),
        migrations.AlterField(
            model_name="order",
            name="is_processed",
            field=models.BooleanField(default=True, verbose_name="Is processed"),
        ),
    ]
