# Generated by Django 4.2.5 on 2023-12-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_remove_order_address_remove_order_id_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderposition",
            name="count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
